<?php

namespace Database\Seeders;

use App\Models\Agbpage;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class AgbpageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        $agbpages = array(
            array('heading' => '1. Geltung ','para1' => '1.1. Unsere Lieferungen, Leistungen und Angebote erfolgen ausschließlich aufgrund dieser AGBs. Diese gelten auch für alle künftigen Vertragsabschlüsse. Auch wenn sie nicht nochmals ausdrücklich vereinbart werden. Geschäftsbedingungen unserer Kunden wird widersprochen, sie finden keine Anwendung.','para2' => '.2. Abweichungen von diesen Geschäftsbedingungen bedürfen unserer ausdrücklichen schriftlichen Anerkennung. Mündliche Nebenabreden sind nicht gültig.','para3' => '1.3. Das Rechtsverhältnis zwischen Auftraggeber und Auftragnehmer ist – soweit ein bestimmter Erfolg herbeigeführt worden ist – Werkvertrag, sonst hinsichtlich der Leistung des Auftragnehmers Dienstvertrag.','para4' => NULL,'para5' => NULL,'status' => '1','deleted_at' => NULL,'created_at' => now(),'updated_at' => now()),
            array('heading' => '2. Auftragsdurchführung','para1' => '2.1. Der Auftragnehmer ist verpflichtet, den ihm erteilten Auftrag nach bestem Wissen und Gewissen mit der geschäftsüblichen Sorgfalt auszuführen. Die gesamte Art und Weise der Durchführung des erteilten Auftrages bestimmt allein der Auftragnehmer. Er hat das Recht, allein die Art und Weise der Durchführung, die Zahl der einzusetzenden Personen, die Erteilung von Unteraufträgen an Dritte etc. zu bestimmen.','para2' => '2.2. Der Auftragnehmer unterliegt Dritten gegenüber der Schweigepflicht.','para3' => NULL,'para4' => NULL,'para5' => NULL,'status' => '1','deleted_at' => NULL,'created_at' => now(),'updated_at' => now()),
            array('heading' => '3. Haftung','para1' => '3.1. Der Auftragnehmer haftet nur bei vorsätzlichen oder grob fahrlässigen Verstößen gegen die geschäftsübliche Sorgfalt.','para2' => '3.2. Eine weitergehende Haftung wird für den Auftragnehmer und seine Mitarbeiter sowie von ihm beauftragte Dritte ausgeschlossen. Insbesondere wird nicht für Entscheidungen oder Beschlüsse gehaftet, die aufgrund eines Berichtes des Auftragnehmers gefasst werden.','para3' => NULL,'para4' => NULL,'para5' => NULL,'status' => '1','deleted_at' => NULL,'created_at' => now(),'updated_at' => now()),
            array('heading' => '4. Pflichten des Auftraggebers','para1' => '4.1. Alle Auskünfte des Auftragnehmers werden in Wahrnehmung berechtigter Interessen erteilt, sind nur für den Auftraggeber bestimmt und von diesem streng vertraulich zu behandeln.','para2' => '4.2. Der Auftraggeber haftet, wenn er vom Auftragnehmer erlangte Informationen vereinbarungswidrig an Dritte weiterleitet.','para3' => '4.3. Der Auftraggeber verpflichtet sich, während der Tätigkeit des Auftragnehmers in gleicher Sache nicht selbst tätig zu werden oder Dritte tätig werden zu lassen.','para4' => '4.4. Der Auftraggeber versichert mit Unterzeichnung des Auftrages, dass er keine staatsgefährdenden oder gesetzeswidrigen Ziele mit dem Auftrag verfolgt.','para5' => NULL,'status' => '1','deleted_at' => NULL,'created_at' => now(),'updated_at' => now()),
            array('heading' => '5. Kündigung','para1' => '5.1. Der Auftraggeber kann bis 3 Tage vor Vertragsbeginn, der Auftragnehmer nur bei Vorliegen eines wichtigen Grundes, kündigen. Tritt der Auftraggeber weniger als 3 Tage vor Auftragsbeginn vom Vertrag zurück, hat der Auftragnehmer Anspruch auf 50 % der vertraglich vereinbarten Vergütung, mindestens aber auf € 500,00 als Aufwandsentschädigung.','para2' => '5.2. Unwahre oder zurückgehaltene Angaben des Auftraggebers berechtigen den Auftragnehmer zur sofortigen Kündigung. Bei vorzeitiger Beendigung des Auftragsverhältnisses hat der Auftragnehmer Anspruch auf das bis zum Wirksamwerden der Kündigung angelaufene Honorar und auf Erstattung der bis dahin entstandenen Aufwendungen. Die Geltendmachung eines weitergehenden Vertrauensschadens bleibt nicht ausgeschlossen.','para3' => '5.3. Im Rahmen eines erteilten Auftrages darf der Auftragnehmer nicht gegen die Interessen des Auftraggebers tätig werden. Ergibt sich im Laufe der Durchführung eines Auftrages jedoch eine Interessenkollision, so darf der Auftragnehmer unter Hinweis darauf vom Vertrag zurücktreten.','para4' => NULL,'para5' => NULL,'status' => '1','deleted_at' => NULL,'created_at' => now(),'updated_at' => now()),
            array('heading' => '6. Vergütung','para1' => '6.1. Die Erledigung des Auftrages kann von einer angemessenen Vorschusszahlung abhängig gemacht werden. Nach Verbrauch des Vorschusses kann der Auftragnehmer die Arbeit bis zu einer erneuten Vorschusszahlung unterbrechen.','para2' => '6.2. Sachdienliche Aufwendungen, der Einsatz technischer Hilfsmittel sowie sonstige im Zusammenhang mit dem Auftrag anfallende Kosten (z.B. Übernachtungskosten, Taxi- und Bahnfahrten etc.) sind vom Auftraggeber gesondert zu vergüten.','para3' => '6.3. Wird der Auftragnehmer infolge der Ausführung des Auftrages in Prozesse oder sonstige Verfahren durch Anhörung oder schriftliche Stellungnahme in Anspruch genommen, so ist der Auftraggeber verpflichtet, den Zeitaufwand und die Auslagen gemäß den Sätzen des Auftragnehmers zu vergüten. Vom Gericht für die Inanspruchnahme gezahlte Entschädigungen sind auf die Vergütung des Auftragnehmers anzurechnen.','para4' => NULL,'para5' => NULL,'status' => '1','deleted_at' => NULL,'created_at' => now(),'updated_at' => now()),
            array('heading' => '7. Zahlung','para1' => '7.1. Alle Preise des Auftragnehmers verstehen sich zuzüglich Umsatzwertsteuer. Rechnungen des Auftragnehmers sind 10 Tage nach Rechnungsdatum fällig.','para2' => '7.3. Die Hereingabe von Wechseln ist nicht zulässig.','para3' => '7.4. Sollte der Rechnungsbetrag 20 Tage nach Rechnungsdatum nicht vollständig beglichen sein, werden – unter Vorbehalt der Geltendmachung eines weiteren Schadens – Zinsen in Höhe der banküblichen Debetzinsen, mindestens 5 % über dem jeweiligen Bundesbank-Diskontsatz, berechnet.','para4' => '7.5. Bei Zahlungsverzug und begründeten Zweifeln an der Zahlungsfähigkeit oder Kreditwürdigkeit des Auftraggebers ist der Auftragnehmer – unbeschadet seiner sonstigen Rechte – befugt, alle Tätigkeiten sofort einzustellen, Sicherheiten oder Vorauszahlungen für ausstehende Leistungen, Lieferungen, Forderungen etc. zu verlangen und sämtliche Ansprüche aus der Geschäftsverbindung sogleich fällig zu stellen.','para5' => '7.6. Nur unbestrittene oder rechtskräftig festgestellte Forderungen berechtigen den Auftraggeber zu einer Aufrechnung oder Zurückbehaltung.','status' => '1','deleted_at' => NULL,'created_at' => now(),'updated_at' => now()),
            array('heading' => '8. Gerichtsstand','para1' => '8.1. Es gilt das Recht der Bundesrepublik Deutschland als vereinbart.','para2' => '8.2. Gerichtsstand für alle Streitigkeiten aus diesem Vertrag ist Berlin. 9. Wirksamkeit bei Teilnichtigkeit: Falls einzelne Bestimmungen dieser AGB unwirksam sein oder werden sollten, wird die Wirksamkeit der übrigen Bestimmungen dadurch nicht berührt. Die unwirksame Bestimmung ist durch eine gültige zu ersetzen, die dem angestrebten Ziel möglichst nahe kommt.','para3' => NULL,'para4' => NULL,'para5' => NULL,'status' => '1','deleted_at' => NULL,'created_at' => now(),'updated_at' => now())
          );

          foreach ( $agbpages as $key => $name) {
            Agbpage::create($name);
        }
    }
}
