<?php

namespace Database\Seeders;

use App\Models\ServicesPageSection;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ServicesPageSectionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //


          /* `active_security`.`services_page_sections` */
            $services_page_sections = array(
                array('page_cat_id' => '1','heading' => 'Wir schützen Sie mit Erfahrung.','title' => 'Ihr DEKRA zertifizierter Werk- und Objektschutz in Bayern.','sec_image' => '1668494340_s1-img-1.jpg','link' => NULL,'para1' => 'Beim Objektschutz stellen wir die Sicherheit von Industrie- und Firmengebäuden sicher. active security schützt Ihre Objekte durch intensive und zuverlässige Objektbewachung vor Sachbeschädigung, Vandalismus, Diebstahl und Einbruch. Unsere Security Guards übernehmen dabei die Überwachung und Kontrolle des Personen-, Fahrzeug- und Warenverkehrs, die Verwaltung von Schlüsseln und Keycards, Kontrollgänge im Innen- und Außenbereich, die Zutrittskontrolle von Mitarbeitern und Besuchern sowie die Ausstellung und Verwaltung von Mitarbeiter- und Besucherausweisen.','para2' => 'Wir erarbeiten im Vorfeld ein Sicherheitskonzept zum Gebäude- bzw. Objektschutz, das exakt auf Ihre Anforderungen zugeschnitten ist. Bei der anschließenden Objektbewachung überprüfen wir mit regelmäßigen Kontrollmaßnahmen, ob die Sicherheit Ihres Objektes gewährleistet ist - und ergreifen im Ernstfall effiziente Maßnahmen, um den Objektschutz unmittelbar wiederherzustellen.','para3' => NULL,'para4' => NULL,'para5' => NULL,'para6' => NULL,'status' => '1','deleted_at' => NULL,'created_at' => '2022-11-15 06:39:00','updated_at' => '2022-11-15 06:39:00'),
                array('page_cat_id' => '2','heading' => 'Shopping, aber Sicher!','title' => 'in hoch frequentierten Einkaufszentren ist eine anspruchsvolle Sicherheitslösung erforderlich.','sec_image' => '1670929466_up_desk.png','link' => NULL,'para1' => 'Die Sicherheit von Einkaufszentren, Einkaufspassagen und Geschäften ist unser Spezialgebiet. Unsere ausgebildeten und uniformierten Security Guards sichern moderne Einkaufscenter mit geschultem Auge, exakt nach Ihren Vorgaben gegen Vandalismus und Sachbeschädnigung ab.','para2' => 'Dafür arbeiten wir eng mit Ihrem Center-Management und internen Technikern zusammen, um mit ortskundigen Informationen die höchste Sicherheit für Ihr Objekt gewährleisten zu können.','para3' => 'Bei der Bewachung von Einkaufscentern haben Kundenorientierung, Freundlichkeit und Hilfsbereitschaft für uns absolute Priorität. So können wir sicherstellen, dass sich unsere Security Guards optimal in den laufenden Betrieb integrieren und den Service-Gedanken Ihres Unternehmens zusätzlich nach außen transportieren.','para4' => NULL,'para5' => NULL,'para6' => NULL,'status' => '1','deleted_at' => NULL,'created_at' => '2022-11-15 06:44:47','updated_at' => '2022-11-21 07:58:57'),
                array('page_cat_id' => '3','heading' => 'Ladendiebstahl verhindern.','title' => 'Kaufhausdetektive und Diebstahlschutz für den Einzelhandel.','sec_image' => '1668494742_s3-img-1.jpg','link' => NULL,'para1' => 'Mit active security haben Sie einen verlässlichen Partner an Ihrer Seite, der Sie bei der Vermeidung und Aufklärung von Diebstahl-Delikten unterstützt. Wir observieren verdächtige Personen und erkennen potentielle Ladendiebe frühzeitig.','para2' => 'Als Kaufhausdetektive sind wir im Umgang mit den neuesten Kamera- und Sicherheitssystemen geschult, decken Diebstähle auf, sichern Beweismaterial und setzen das Hausrecht durch. Wir unterstützen Sie außerdem bei der fortlaufenden Analyse von Diebstählen und geben Ihnen konkrete Maßnahmen an die Hand, die Sie zur verbesserten Prävention tätigen können.','para3' => 'Unser Sicherheitsdienst verfügt über langjährige Erfahrung bei der Prävention und Aufdeckung von Ladendiebstählen. Unsere Ladendetektive sind in Kaufhäusern, Supermärkten und im Einzelhandel tätig. Wir arbeiten stets diskret und sorgen durch unser professionelles Auftreten für einen reibungslosen Ablauf Ihres Tagesgeschäfts.','para4' => NULL,'para5' => NULL,'para6' => NULL,'status' => '1','deleted_at' => NULL,'created_at' => '2022-11-15 06:45:42','updated_at' => '2022-11-15 06:45:42'),
                array('page_cat_id' => '4','heading' => 'Baustellen mit uns sicher machen.','title' => 'Erst die Analayse, dann die Planung.','sec_image' => '1668494794_s4-img-1.jpg','link' => NULL,'para1' => 'Bei der Baustellenbewachung sichert unser Wachdienst gewerbliche Baustellen ab und schützt diese vor ungebetenen Eindringlingen und Diebstahl. Da jede Baustelle anders ist, können im Zuge der Bewachung Ihrer Baustelle verschiedene Komponenten zum Einsatz kommen. So bieten wir Ihnen verschieden Sicherheitsdienst-Leistungen an.','para2' => 'Wir übernehmen für Sie die Öffnung und Schließung Ihrer Baustelle, überwachen die Zugänge und erstellen Baustellenausweise für Ihre Mitarbeiter und Besucher und ebenso auch die Notfallversorgung durch den Einsatz von ausgebildeten Betriebssanitätern.','para3' => 'Um Ihre Baustelle auch nachts optimal schützen zu können, wird bei Bedarf das Gelände regelmäßig durch eine Sicherheitsstreife kontrolliert.','para4' => NULL,'para5' => NULL,'para6' => NULL,'status' => '1','deleted_at' => NULL,'created_at' => '2022-11-15 06:46:34','updated_at' => '2022-11-15 06:46:34'),
                array('page_cat_id' => '5','heading' => 'Schließen Sie Sicherheitsrisiken aus.','title' => 'Der Öffnung- und Schließdienst von active security.','sec_image' => '1668494848_s5-img-1.jpg','link' => NULL,'para1' => 'Unser Sicherheitsdienst bietet Ihnen einen ordnungsgemäßen Öffnungs- und Schließdienst für Objekte wie Kaufhäuser, Supermärkte, Geschäfte, öffentliche Einrichtungen, Veranstaltungsräumlichkeiten oder auch Freiflächen, die durch Zäune, Zufahrten oder Tore eingegrenzt werden.','para2' => 'Unser Öffnungs- und Schließdienst erfolgt exakt nach einem Schließplan, den wir im Vorfeld mit Ihnen aufsetzen. Wir kontrollieren die Schlüsselausgabe und -annahme, übernehmen die Alarm-Scharfschaltung nach Ladenschluss, überprüfen alle Fenster und Türen und sorgen für den korrekten Vollverschluss von Objekten und Geschäftsräumen, um diese vor Einbruch, Diebstahl und Sachbeschädigung zu schützen. Am nächsten Tag übernimmt unser Öffnungsdienst das Aufsperren Ihrer Räumlichkeiten und deaktiviert die zuvor scharf geschaltete Alarmsicherung.','para3' => 'Übrigens: Reichen Sie unser Sicherheitskonzept bei Ihrer Versicherung ein, um ggf. eine Reduzierung Ihrer Versicherungskosten zu erhalten.','para4' => NULL,'para5' => NULL,'para6' => NULL,'status' => '1','deleted_at' => NULL,'created_at' => '2022-11-15 06:47:28','updated_at' => '2022-11-15 06:47:28'),
                array('page_cat_id' => '6','heading' => 'Mobiler Wachdienst.','title' => 'Zusätzliche Sicherheit, auf Ihren Bedarf abgestimmt.','sec_image' => '1668494905_s6-img-1.jpg','link' => NULL,'para1' => 'Mit unserem mobilen Revierwachdienst verhindern Sie Einbruch und Schäden an Ihren Objekten und umliegenden Geländen. Wir bewachen Büroräume, Lager- und Industriehallen, IT- und Rechenzentren, sowie private Anwesen. Rund um die Uhr, an 365 Tagen im Jahr.','para2' => 'Beim Revierdienst versieht der Security Manager alle sicherheitskritischen Checkpoints nach abgeschlossener Planung mit digitalen Stechstellen. Unser Revier- und Streifendienst fährt diese Punkte dann zu vereinbarten Kontrollzeiten ab. Nachdem alle für den Standort festgelegten Arbeitsschritte erledigt wurden, sendet das IT-basierte Wächter-Kontrollsystem automatisch ein Signal an die Zentrale. Dadurch können Sie die Umsetzung des Maßnahmen-Katalogs zu jeder Zeit nachverfolgen.','para3' => 'Übrigens: Bei Interesse an einer 24-Stunden-Bewachung eignet sich unser Leistungsportfolio im Rahmen des Objektschutzes.','para4' => NULL,'para5' => NULL,'para6' => NULL,'status' => '1','deleted_at' => NULL,'created_at' => '2022-11-15 06:48:25','updated_at' => '2022-11-15 06:48:25'),
                array('page_cat_id' => '7','heading' => 'Kundenorientiert und engagiert.','title' => 'Für uns steht der Servicegedanke im Fokus.','sec_image' => '1669017608_P1370445-Edit 1.jpg','link' => NULL,'para1' => 'In Ihrem Unternehmen herrscht reger Personenverkehr - und wir sorgen dafür, dass dieser optimal koordiniert wird. Unser Empfangsdienst kommt häufig in sensiblen bzw. beengten Eingangsbereichen zum Einsatz. Wir begrüßen Besucher, überprüfen Mitarbeiterausweise und kontrollieren eintreffende Lieferanten. Zeitgleich werden Anrufer von uns kompetent und freundlich zu den gewünschten Gesprächspartnern vermittelt und eingehende E-Mails bearbeitet. Zum Empfangsdienst gehören außerdem die Koordination aller relevanten Informationen sowie die Verwaltung von Schlüsseln und Zugängen.','para2' => 'Was unsere Kunden am Empfangsdienst von active security schätzen?','para3' => 'Ganz klar: Unser Empfangspersonal versteht sich als serviceorientierter Gastgeber unserer Kunden. Wir überzeugen mit einem gepflegten Erscheinungsbild und einem professionellen Auftreten, bewahren auch in herausfordernden Situationen den Überblick und begegnen Ihnen und Ihren Kunden stets freundlich und zuvorkommend.','para4' => NULL,'para5' => NULL,'para6' => NULL,'status' => '1','deleted_at' => NULL,'created_at' => '2022-11-15 06:49:21','updated_at' => '2022-11-21 08:00:08'),
                array('page_cat_id' => '8','heading' => 'Präventive Sicherheit am Eingang','title' => 'Die ideale Sicherheitslösung für den Handel.','sec_image' => '1668495017_s8-img-1.jpg','link' => NULL,'para1' => 'Shop Guards sind ausgebildete Sicherheitsfachkräfte, die durch ihre Präsenz Diebstählen und Raubüberfällen vorbeugen und mögliche Täter abschrecken.','para2' => 'Unsere Shop Guards setzen sich aus einem erfahrenen und geschulten Team zusammen, um Übergriffe und Diebstähle präventiv zu verhindern oder im Ernstfall angemessen zu reagieren und kritische Situationen zu deeskalieren. Sie empfangen Ihre Kunden und stehen diesen mit absoluter Servicebereitschaft auch bei Fragen zur Verfügung.','para3' => 'Der Shop Guard ist bei Konflikten immer zur Stelle und im Eingangsbereich präsent.','para4' => NULL,'para5' => NULL,'para6' => NULL,'status' => '1','deleted_at' => NULL,'created_at' => '2022-11-15 06:50:17','updated_at' => '2022-11-15 06:50:17'),
                array('page_cat_id' => '9','heading' => 'jede Art von Veranstaltung.','title' => 'Ein umfassender Schutz für Ihr geplantes Event.','sec_image' => '1668495079_s9-img-1.jpg','link' => NULL,'para1' => 'Selbst bei kleinen Veranstaltungen ist ein verlässlicher Sicherheitsdienst nicht mehr wegzudenken. Der reibungslose Ablauf eines solchen Events wird von unseren Security Guards gewährleistet. Die Event Security übernimmt dabei u.a. die Regelung des Verkehrs auf dem Parkplatz sowie die Einlasskontrolle. Für den umfassenden Schutz von Personen und Eigentum empfehlen wir außerdem, die Überwachung des Geländes bereits während des Aufbaus einzusetzen. Aber auch nach dem Ende der Veranstaltung bleiben wir für Sie mit unserer Security vor Ort.','para2' => 'Damit Ihre Veranstaltung allen Ansprüchen gerecht wird, setzen wir bereits bei der Planung auf routinierte Abläufe sowie die Einhaltung aller sicherheitsrelevanten, organisatorischen Maßnahmen. Egal ob es sich dabei um Konzerte, Sportveranstaltungen oder Messen handelt - mit dem Veranstaltungsschutz von active security wird Ihr Event zum vollen Erfolg!','para3' => NULL,'para4' => NULL,'para5' => NULL,'para6' => NULL,'status' => '1','deleted_at' => NULL,'created_at' => '2022-11-15 06:51:19','updated_at' => '2022-11-15 06:51:19')
            );
  
          foreach ( $services_page_sections as $key => $name) {
            ServicesPageSection::create($name);
        }
    }
}
